apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: threa-data
  namespace: threa
  labels:
    app.kubernetes.io/component: storage
    app.kubernetes.io/name: threa
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
