apiVersion: v1
kind: Service
metadata:
  name: threa
  namespace: threa
  labels:
    app.kubernetes.io/component: service
    app.kubernetes.io/name: threa
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: threa
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
